import type { StoneSample } from "@/types/content";

type BrandSeed = {
  manufacturer: string;
  items: string[];
};

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9а-яё]+/gi, "-")
    .replace(/^-+|-+$/g, "");
}

function inferFinish(title: string) {
  return /(мат|mat|матовый|honed|seta)/i.test(title) ? "Матовая" : "Полированная";
}

function inferColor(title: string) {
  const source = title.toLowerCase();
  if (/(black|nero|noir|темн|черн)/i.test(source)) return "Черный";
  if (/(white|bianco|blanc|snow|ice|polar|снег|бел)/i.test(source)) return "Белый";
  if (/(grey|gray|grigio|gris|бетон|concrete|silver)/i.test(source)) return "Серый";
  if (/(beige|ivory|sand|taj|cream|gold|aurelia|terracotta)/i.test(source)) return "Бежевый";
  if (/(brown|mocca|coffee|emperador|chocolate)/i.test(source)) return "Коричневый";
  if (/(blue|azul|ocean|aquamarine)/i.test(source)) return "Синий";
  return "Микс";
}

function inferTexture(title: string) {
  const source = title.toLowerCase();
  if (/(calacatta|statuario|carrara|arabesc|marquina|patagonia|onyx|taj|travertin|venato)/i.test(source)) {
    return "Мраморная";
  }
  if (/(concrete|beton|urban|cemento|oxid|materica|rusty)/i.test(source)) {
    return "Бетонная";
  }
  return "Каменная";
}

function inferThicknesses(title: string) {
  if (/\b5 ?мм|\(5мм\)/i.test(title)) {
    return ["5 мм"];
  }
  if (/\b8 ?мм/i.test(title)) {
    return ["8 мм", "20 мм"];
  }
  return ["20 мм", "30 мм"];
}

function makeStones(seed: BrandSeed): StoneSample[] {
  const brandSlug = slugify(seed.manufacturer.replace(/quartz/gi, "").trim());
  return seed.items.map((title, index) => ({
    id: `stone_${brandSlug}_${index + 1}`,
    slug: `${brandSlug}-${slugify(title)}`,
    title,
    stoneType: "quartz",
    manufacturer: seed.manufacturer,
    color: inferColor(title),
    texture: inferTexture(title),
    thicknesses: inferThicknesses(title),
    finish: inferFinish(title),
    description: `Кварцевый агломерат ${seed.manufacturer} для кухонь, ванных и коммерческих пространств.`,
    image: "/images/quartz-surface-light.svg",
    isFeatured: index < 4,
    priceFrom: null
  }));
}

const seeds: BrandSeed[] = [
  {
    manufacturer: "Avant Quartz",
    items: [
      "1000 Дижон",
      "1012 Амьен",
      "1220 Клермон",
      "1111 Авалон",
      "2060 Грей Тур",
      "9023 Лотарингия",
      "9133 Авиньон Грис",
      "9603 Сен-Мало",
      "9005 Бурбонне",
      "9006 Лимузен",
      "9010 Корсика",
      "9212 Сен-Тропе",
      "9510 Ванилла Анси",
      "9050 Грис Фонсе",
      "9172 Блаве",
      "9173 Вилен",
      "8044 Эври (Матовый)",
      "8011 Нант (Матовый)",
      "8033 Каркассон (Матовый)",
      "8059 Лаваль (Матовый)",
      "8100 Мулен (Матовый)",
      "8800 Кассис (Матовый)",
      "8810 Ренн Тэмпл (Матовый)",
      "8811 Резе (Матовый)",
      "8046 Эсон (Матовый)",
      "8580 Тарн (Матовый)",
      "7000 Калакатта Эно",
      "7030 Калакатта Шенонсо",
      "7040 Калакатта Бомениль",
      "7060 Калакатта Мон Сен-Мишель",
      "7070 Калакатта Версаль",
      "7080 Калакатта Пьерфон",
      "7090 Калакатта Рона-Альпы",
      "7100 Статуарио Лилль",
      "7200 Аквитания Бланка",
      "7400 Калакатта Дофине",
      "7470 Калакатта Берн",
      "7500 Калакатта Аррас",
      "7550 Калакатта Канны Голд (Мат)",
      "7560 Калакатта Альби (Мат)",
      "7570 Калакатта Таланс",
      "7630 Калакатта Венсен",
      "7670 Калакатта Кассель",
      "7700 Калакатта Марсель",
      "7888 Калакатта Динан",
      "7970 Калакатта Труа",
      "7980 Ницца Бланк",
      "7985 Ницца Ноир (Мат)",
      "7810 Калакатта Модан",
      "5751 Калакатта Бессон (Print)",
      "5752 Калакатта Креспен (Print)",
      "5753 Калакатта Аверон (Print)",
      "5754 Калакатта Вивье (Print)",
      "5700 Калакатта Амели (Print)",
      "5750 Калакатта Шери (Print)",
      "5800 Травертин Супп (Print)"
    ]
  },
  {
    manufacturer: "Avarus",
    items: [
      "R112 Соль Каспия",
      "R122 Алмазы Якутии",
      "R104 Белая Тайга",
      "R515 Вулканы Камчатки",
      "R403 Скалы Карелии",
      "R444 Ай-Петри",
      "R500 Жемчуг Приморья",
      "R503 Уральские Горы",
      "R510 Черное Море",
      "R511 Лёд Байкала",
      "R520 Астраханские Пески",
      "R522 Золотое Кольцо",
      "R531 Донская Степь",
      "R538 Горы Кавказа",
      "R541 Снега Сибири",
      "R543 Пик Эльбруса",
      "R555 Балтийский Берег",
      "R558 Просторы Поволжья",
      "R575 Красная Поляна",
      "R590 Северное Сияние",
      "R677 Московская ночь",
      "RM104 Белая Тайга Мат",
      "RM403 Скалы Карелии Мат",
      "RM444 Ай-Петри Мат",
      "RM500 Жемчуг Приморья Мат",
      "RM510 Черное Море Мат",
      "RM511 Лёд Байкала Мат",
      "RM520 Астраханские Пески Мат",
      "RM543 Пик Эльбруса Мат",
      "RM560 Золотые Ворота Мат"
    ]
  },
  {
    manufacturer: "Smart Quartz",
    items: [
      "White Sand",
      "Silver Night",
      "Sunshine",
      "Linen",
      "White Marble",
      "Super White",
      "Negro Imperial",
      "Illusion",
      "Bianco Venatino",
      "Crema Marfil (Матовый)",
      "Coffee Brown (Матовый)",
      "Giallo",
      "Munsell",
      "Russet",
      "Moon White (Матовый)",
      "Moon Grey (Матовый)",
      "Bianco Lasa",
      "Calacatta Moon",
      "Calacatta Sun",
      "Calacatta Tree",
      "Gold Arabescato",
      "Statuario Gold",
      "Rockland (матовый)",
      "Coral (матовый)",
      "Slate (матовый)",
      "Antracite",
      "Marquina",
      "Black Jasper (матовый)",
      "Titanium",
      "Patagonia",
      "Jasmine",
      "Taj Mahal (матовый)"
    ]
  },
  {
    manufacturer: "Noblle Quartz",
    items: [
      "Q117 Jade White",
      "Q131 Black Sand",
      "Q716 Carrara Sun",
      "Q718 Carrara Moon",
      "Q719 Carrara Black",
      "Q717 Bianco Giogia",
      "Q735 Bianco Venato",
      "Q740 Calacatta Venato",
      "Q744 Calacatta Bianco",
      "Q765 Nero Marquina",
      "Q785 Calacatta Gold",
      "Q810 Grey Glow",
      "Q811 Beton White (мат)",
      "Q859 Beton Brass (мат)",
      "Q880 Beton Grey (мат)",
      "Q703 Calacatta Borghini",
      "Q707 Sahara Noir",
      "Q757 Calacatta Aurum",
      "Q798 Calacatta Elegant",
      "Q840 White Misterio",
      "Q850 Urban Grigio",
      "Q795 Calacatta Magic Dark",
      "Q796 Calacatta Magic White",
      "Q797 Calacatta True Light",
      "Q901 Patagonia Gold",
      "Q902 Patagonia Platinum",
      "Q921 Arabescato Black",
      "Q922 Arabescato White",
      "Q923 Arabescato Corchia",
      "Q650 Pietra Grigia",
      "Q750 Statuario Classic",
      "Q790 Venato Royal"
    ]
  },
  {
    manufacturer: "Etna Quartz",
    items: [
      "EQHM 001 Perlino Bianco",
      "EQHM 002 Calacatta Venato",
      "EQHM 003 Canvas",
      "EQHG 004 Canvas",
      "EQHG 004 Canvas (матовый)",
      "EQHM 005 Mandala",
      "EQHM 006 Negro Marquina",
      "EQHM 007 Grey Marquina",
      "EQHM 007 Grey Marquina (мат)",
      "EQPM 008 Calacatta Santorini",
      "EQT 017 Bianco Extra",
      "EQT 017 Bianco Extra (мат)",
      "EQTM 018 Calacatta Borghini",
      "EQPM 020 Sofita Beige",
      "EQPG 022 Bianco Antico",
      "EQPM 023 White Ice",
      "EQPM 025 Azul Imperiale",
      "EQPM 026 Brown Perlino",
      "EQPM 027 Ambra",
      "EQPM 028 Black Perlino",
      "EQHM 029 Sahara Noir",
      "EQAC 036 Antica Grey",
      "EQAM 042 Volakas Extra",
      "EQAM 043 Bianco Crystallo",
      "EQAM 046 Arabescato Corcia",
      "EQJC 052 Black Mirror",
      "EQJC 054 Antica Dark Bronze (Мат)",
      "EQCM 059 Canvas Gold",
      "EQCC 061 Antico Classic (Мат)",
      "EQC 067 Pure White",
      "EQPM 068 Panda White",
      "EQJO 069 Onyx Bianco",
      "EQMM 070 Calacatta Star",
      "EQMM 071 Golden Silk",
      "EQMM 072 Moon Valley",
      "EQJM 073 Calacatta Etna",
      "EQJQ 077 Patagonia Extra",
      "EQMO 079 Aquamarine",
      "EQAG 099 Titanium Leather (Мат)",
      "EQMM 101 Carrara",
      "EQMM 102 Cream Beige",
      "EQMO 103 Ice Onyx",
      "EQMM 104 Etna Delicato"
    ]
  },
  {
    manufacturer: "Caesarstone",
    items: [
      "3141 Osprey",
      "3142 While Shimmer",
      "6141 Ocean Foam",
      "9141 Ice Snow",
      "1141 Pure White",
      "2040 Urban",
      "2141 Snow",
      "2230 Linen",
      "7110 Burnt Cordite",
      "4030 Oyster",
      "4120 Raven",
      "4600 Organic White",
      "3100 Jet Black",
      "4130 Clamshell",
      "4230 Shitake",
      "4350 Mink",
      "5000 London Grey",
      "5003 Piatra Grey",
      "5100 Vanilla Noir",
      "5110 Alpine Mist",
      "5133 Symphony Grey",
      "5141 Frosty Carina",
      "5143 White Attica",
      "5212 Taj Royale",
      "6003 Coastal Grey",
      "6046 Moorland Fog",
      "6131 Bianco Drift",
      "6134 Georgian Bluffs",
      "6313 Turbine Grey",
      "6338 Woodlands",
      "4003 Sleek Concrete (мат)",
      "4011 Cloudbust Concrete (мат)",
      "4023 Topus Concrete (мат)",
      "4033 Rugged Concrete (мат)",
      "4043 Primordia (мат)",
      "4044 Airy Concrete (мат)",
      "4735 Oxidian (мат)",
      "5810 Black Tempal (мат)",
      "5031 Statuario Maximus",
      "5111 Statuario Nuvo",
      "5131 Calacatta Nuvo"
    ]
  },
  {
    manufacturer: "TechniStone",
    items: [
      "Brilliant Arabesco",
      "Crystal Absolute White",
      "Crystal Polar White",
      "Crystal Royal",
      "Gobi Black",
      "Gobi Grey",
      "Morning Daisy (мат)",
      "Noble Arco",
      "Noble Arco (мат)",
      "Noble Areti Bianco",
      "Noble Athos Brown",
      "Noble Botticino",
      "Noble Carrara",
      "Noble Concrete Grey",
      "Noble Concrete Grey (мат)",
      "Noble Imperial Grey",
      "Noble Ivory White",
      "Noble Linea",
      "Noble Olympos Mist",
      "Noble Pietra Grey",
      "Noble Portland Grey",
      "Noble Portland Grey (мат)",
      "Noble Pro Cloud",
      "Noble Pro Frost",
      "Noble Pro Storm",
      "Noble Quartzite",
      "Noble Quartzite (мат)",
      "Noble Supreme White",
      "Noble Troya",
      "Noble Vintage",
      "Noble Vintage (мат)",
      "Pearl Delta",
      "Taurus Black",
      "Taurus Terazzo Dark",
      "Taurus Terazzo Dark (мат)",
      "Taurus Terazzo Grey",
      "Taurus Terazzo White",
      "Wedding Lily (мат)",
      "Wild Yucca"
    ]
  },
  {
    manufacturer: "Still Stone",
    items: [
      "G002 White Crystal",
      "GTA023 Ice Crystal",
      "G2807 Black Crystal",
      "GTA1006 Cream Quartz",
      "GT8157 Carrara Extra",
      "GTA026 Milky White",
      "GT8155 Namibia White",
      "GT9690 Arabescato",
      "GT8077 Grapfite Vein",
      "GT8080 Morning Sky",
      "GT8183 Kalahari Sand",
      "GT9001 Milk&Honey",
      "GT9007 Chocolate Brownie",
      "GT9170 Santorini Rock",
      "GT6010 Ural White",
      "GT9680 Sahara Gold",
      "GT9830 Marquina Teide",
      "GT8627 Rhodesia Black",
      "GT9650 Arctica",
      "GT9750 Statuario",
      "GT1990 Calacatta Minore",
      "GT9980 Calacatta Maggiore",
      "GT7040 Calacatta Voski"
    ]
  },
  {
    manufacturer: "Belenco",
    items: [
      "1010 Premium White",
      "1010 Premium White Seta",
      "3110 Polaris",
      "3110 Polaris Seta",
      "3727 Just Black",
      "4110 Diamond White",
      "4262 Kristella White",
      "5050 Forza Fume",
      "5139 Juliet White",
      "5250 Elexir White",
      "5250 Elexir White Seta",
      "5751 Gala Black",
      "6139 Everst White",
      "8250 Columbia Gray",
      "8262 Mont Blanc Snow",
      "8765 Volcano Black",
      "8765 Volcano Black Seta",
      "9242 Arena",
      "9242 Arena Seta",
      "1110 Iceberg",
      "1123 Perla White",
      "1124 Amalfi",
      "1227 Pixie Wings",
      "2214 Teos",
      "2254 Aurora",
      "2543 Ashen",
      "2543 Ashen Seta",
      "2555 Artesia",
      "3113 Daphne Crack",
      "3333 Boletus",
      "3333 Boletus Seta",
      "3555 Parma",
      "3555 Parma Seta",
      "3618 Olympos",
      "4043 Aizano",
      "4043 Aizano Seta",
      "4123 Kashmera White",
      "4217 Rapture",
      "4227 Fairy White",
      "4444 Sahara Beige",
      "4456 Cadiz",
      "4458 Chakra Beige",
      "4524 La Luna",
      "4535 Terre Grey",
      "4558 Babilon",
      "4558 Babilon Seta",
      "5113 Minta",
      "5114 Carola",
      "5224 Elegance",
      "5329 Mocca Mousse",
      "6114 Belluno",
      "6114 Belluno Honed",
      "7123 Carrara Bela",
      "7227 Armilla",
      "7353 Pergamon",
      "7458 Granada",
      "7537 Metropol Grey",
      "7537 Metropol Grey Seta",
      "7543 Montana",
      "8113 Anemon",
      "8123 Carrara Luca",
      "8727 Spa Black",
      "8727 Spa Black Seta",
      "9113 Alinda",
      "1189 Calacatta Garda",
      "1219 Calacatta Victory",
      "1220 Calacatta Paletino",
      "1221 Calacatta Valencia",
      "2219 Calacatta Venezia",
      "2229 Calacatta Venus",
      "3516 Hypnose",
      "4120 Calacatta Alya",
      "4242 Statuario Volga",
      "5219 Statuario Crux",
      "6214 Stardust",
      "6229 Aspendos",
      "7119 Calacatta Venatino",
      "7220 Pantheon",
      "8119 Calacatta Verona",
      "9119 Calacatta Veneto",
      "9219 Marquina Tierra",
      "9219 Marquina Tierra Seta",
      "9719 Marquina Lavanga"
    ]
  },
  {
    manufacturer: "Asterum",
    items: [
      "0001 Perfecta",
      "1001 Coliseum",
      "1101 Megapolis",
      "1104 Macedonia",
      "1105 Trufaldino",
      "3000 Jakarta",
      "3002 Cappucino",
      "3003 Cleopatra",
      "3004 Buckingham",
      "3101 Alaska",
      "3102 Palladium",
      "3103 Leonardo",
      "3104 Tundra",
      "3200 Arabica",
      "3402 Palladium Matt",
      "4002 Derbent",
      "4101 Safary",
      "4102 Husky",
      "4103 Niagara",
      "4104 Bionica",
      "5001 Albion",
      "5002 Caracum",
      "5003 Michelangelo",
      "5101 Everest",
      "5108 Vanessa",
      "5109 Picanto",
      "5110 Charaur",
      "5400 Himalayas Matt",
      "5401 Aurelia Matt",
      "6101 Archeolog",
      "6106 Bagira",
      "7401 Hippy Matt"
    ]
  },
  {
    manufacturer: "Vicostone",
    items: [
      "BQ 5260 Beton (5мм) (Мат)",
      "BQ 5261 Materica (5мм) (Мат)",
      "BQ 5290 Nube (5мм) (Мат)",
      "BQ 5291 Rusty (5мм) (Мат)",
      "BQ 5860 Corazon (5мм) (Мат)",
      "BQ 5862 Oceanid (5мм) (Мат)",
      "BS 124 Satined",
      "BQ 2101 Pure Black",
      "BQ 8220 Carrara",
      "BQ 8590 Dolce Vita",
      "BQ 8815 Misterio",
      "BQ 8740 Nero Marquina",
      "BQ 2605 Denali (Мат)",
      "BQ 3603 Galilea (Мат)",
      "BQ 6800 Grey Monet (Мат)",
      "BQ 8730 Cemento (Мат)",
      "BQ 8860 Concreto (Мат)",
      "BQ 8863 Tartufo (Мат)",
      "BQ 8864 Naxos (Мат)",
      "BQ 8870 Olympus White (Мат)",
      "BQ 8891 Madreperola (Мат)",
      "BQ 8926 Calacatta Caldia (Мат)",
      "BQ 200 Artic Snow",
      "BQ 2600 Valley White",
      "BQ 2607 Serizzo Monterosa",
      "BQ 100 Quasar Light",
      "BQ 7702 Moonglade",
      "BQ 8402 Delta",
      "BQ 8430 Botticino Classic",
      "BQ 8440 Bianco Venato",
      "BQ 8560 Dark Emperador",
      "BQ 8614 Altissimo",
      "BQ 8668 Ice Lake",
      "BQ 8786 Thunder Blue",
      "BQ 8812 Java Noir",
      "BQ 8820 Misterio Gold",
      "BQ 9310 Silver Sea",
      "BQ 9453 Taj Mahal",
      "BQ 9470 Azul Aran",
      "BQ 6700 Covelani",
      "BQ 6701 Camarina",
      "BQ 6702 Costa Nova",
      "BQ 8583 Akoya",
      "BQ 8628 Statuario",
      "BQ 8660 Venatino",
      "BQ 8738 Greylac",
      "BQ 8780 Argento",
      "BQ 8788 Diamante",
      "BQ 8800 Bettoglio",
      "BQ 8881 Gan Eden",
      "BQ 8887 Amadeus",
      "BQ 8918 Vivalioro",
      "BQ 8920 Forza",
      "BQ 9700 Sahara Noir"
    ]
  },
  {
    manufacturer: "Quantra Quartz",
    items: [
      "2442 Semolina",
      "2456 Brown Leaf",
      "1673 New Carrara",
      "2455 Ancient Beige",
      "6589 Classic Ivory",
      "7172 Arctic Breeze",
      "2430 Artisan Wool",
      "7111 Agnolo Matt",
      "7447 Bianco Venatino",
      "7448 Bellini Matt",
      "7500 Masaccio",
      "7511 Botticelli",
      "7522 Raphael",
      "7700 Antonio",
      "7982 Rogier",
      "9334 Calacatta Capri",
      "9333 Calacatta Oro",
      "9010 Calacatta Luca",
      "9444 Calacatta Borghini",
      "8058 Hermes Grey Matt",
      "9510 Cygnus Divine",
      "9965 Golden Gate",
      "9953 Sevilia",
      "9976 Pirouette",
      "9996 Leonardo",
      "9972 San Marco",
      "9987 Champs-Elysees",
      "9986 Fontainebleau",
      "9960 Pantheon",
      "9962 La Dolce Vita",
      "2048 Snow White"
    ]
  },
  {
    manufacturer: "Aleph Stone",
    items: [
      "A35 Bianco Marble",
      "A30 Ultra White",
      "A33 Carrara Ideal",
      "A63 Artico",
      "A69 Artico Perlato (Мат)",
      "A70 Arabescato White",
      "A80 Statuario NG",
      "A82 Golden Age",
      "A60 Calacatta Spring",
      "A62 Calacatta Lincoln",
      "A66 Storm Grey (Мат)",
      "A78 Arabescato Notte",
      "A87 Ariston",
      "A75 Arabescato Delicato",
      "A76 Arabescato Miele",
      "A77 Arabescato Nature",
      "A79 Arabescato Irish",
      "A91 Travertino",
      "A93 Taj Mahal",
      "A95 Desert Rose",
      "A96 Ivory Glace",
      "A97 Onice Ambra",
      "A90 Solomeo (Мат)",
      "A88 Calacatta Luxe",
      "A89 Emperador",
      "A92 Onyx Blue",
      "A94 Onyx Bianco",
      "A99 Ocean Grey",
      "A100 Clear Quartz"
    ]
  }
];

export const quartzBrandStones: StoneSample[] = seeds.flatMap((seed) => makeStones(seed));
